#pragma checksum "MainWindow.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "7297618FA8334E4709D5C18576B9FB1D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Morabaraba_2;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Morabaraba_2 {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox Container;
        
        #line default
        #line hidden
        
        
        #line 21 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Turn;
        
        #line default
        #line hidden
        
        
        #line 23 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Phase;
        
        #line default
        #line hidden
        
        
        #line 25 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Action;
        
        #line default
        #line hidden
        
        
        #line 27 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button GoToMainMenu;
        
        #line default
        #line hidden
        
        
        #line 30 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox Background1;
        
        #line default
        #line hidden
        
        
        #line 34 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PiecesParent;
        
        #line default
        #line hidden
        
        
        #line 35 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse a7;
        
        #line default
        #line hidden
        
        
        #line 36 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse d7;
        
        #line default
        #line hidden
        
        
        #line 37 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse g7;
        
        #line default
        #line hidden
        
        
        #line 38 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse b6;
        
        #line default
        #line hidden
        
        
        #line 39 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse d6;
        
        #line default
        #line hidden
        
        
        #line 40 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse f6;
        
        #line default
        #line hidden
        
        
        #line 41 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse c5;
        
        #line default
        #line hidden
        
        
        #line 42 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse d5;
        
        #line default
        #line hidden
        
        
        #line 43 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse e5;
        
        #line default
        #line hidden
        
        
        #line 44 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse a4;
        
        #line default
        #line hidden
        
        
        #line 45 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse b4;
        
        #line default
        #line hidden
        
        
        #line 46 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse c4;
        
        #line default
        #line hidden
        
        
        #line 47 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse e4;
        
        #line default
        #line hidden
        
        
        #line 48 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse f4;
        
        #line default
        #line hidden
        
        
        #line 49 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse g4;
        
        #line default
        #line hidden
        
        
        #line 50 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse c3;
        
        #line default
        #line hidden
        
        
        #line 51 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse d3;
        
        #line default
        #line hidden
        
        
        #line 52 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse e3;
        
        #line default
        #line hidden
        
        
        #line 53 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse b2;
        
        #line default
        #line hidden
        
        
        #line 54 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse d2;
        
        #line default
        #line hidden
        
        
        #line 55 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse f2;
        
        #line default
        #line hidden
        
        
        #line 56 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse a1;
        
        #line default
        #line hidden
        
        
        #line 57 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse d1;
        
        #line default
        #line hidden
        
        
        #line 58 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse g1;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Morabaraba-2;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Container = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 2:
            this.Turn = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.Phase = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.Action = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.GoToMainMenu = ((System.Windows.Controls.Button)(target));
            
            #line 27 "MainWindow.xaml"
            this.GoToMainMenu.Click += new System.Windows.RoutedEventHandler(this.GoToMainMenu_MouseDown);
            
            #line default
            #line hidden
            return;
            case 6:
            this.Background1 = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 7:
            this.PiecesParent = ((System.Windows.Controls.Grid)(target));
            
            #line 34 "MainWindow.xaml"
            this.PiecesParent.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Move);
            
            #line default
            #line hidden
            return;
            case 8:
            this.a7 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 9:
            this.d7 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 10:
            this.g7 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 11:
            this.b6 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 12:
            this.d6 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 13:
            this.f6 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 14:
            this.c5 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 15:
            this.d5 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 16:
            this.e5 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 17:
            this.a4 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 18:
            this.b4 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 19:
            this.c4 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 20:
            this.e4 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 21:
            this.f4 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 22:
            this.g4 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 23:
            this.c3 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 24:
            this.d3 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 25:
            this.e3 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 26:
            this.b2 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 27:
            this.d2 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 28:
            this.f2 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 29:
            this.a1 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 30:
            this.d1 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 31:
            this.g1 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

